#include=~/.config/foot/matugen/matugen-foot-colors.ini
#include=~/.config/foot/catppuccin-mocha.ini

[tweak]
font-monospace-warn=no

[main]
term = foot
font = JetBrainsMono Nerd Font:style=Bold:size=12
dpi-aware = no

[cursor]
 style=block
 blink=no
 blink-rate=500
 beam-thickness=1.5

[colors-dark]
foreground=bfbdb6
background=020202
alpha=0.5

regular0=0D0D0D
regular1=f07178
regular2=FF8732  
regular3=aad94c  
regular4=59c2ff
regular5=d2a6ff
regular6=73b8ff
regular7=dedede

bright0=5c6773
bright1=f07178
bright2=ff8f40   
bright3=aad94c   
bright4=59c2ff
bright5=d2a6ff
bright6=73b8ff
bright7=ffffff
