#include=~/.config/foot/matugen/matugen-foot-colors.ini
#include=~/.config/foot/catppuccin-mocha.ini

[tweak]
font-monospace-warn=no

[main]
term = foot
font = JetBrainsMono Nerd Font:style=Bold:size=12
dpi-aware = no

[cursor]
 style=block
 blink=no
 blink-rate=500
 beam-thickness=1.5

[colors-dark]
foreground=e6e1cf
background=0D0D0D
alpha=0.5

regular0=0D0D0D
regular1=f07178
regular2=FF8732  
regular3=aad94c  
regular4=59c2ff
regular5=d2a6ff
regular6=73b8ff
regular7=dedede

bright0=5c6773
bright1=f07178
bright2=ff8f40   
bright3=aad94c   
bright4=59c2ff
bright5=d2a6ff
bright6=73b8ff
bright7=ffffff

16=ff8f40
17=e6b673
18=131721
19=272d38
20=bfbdb6
21=e6e1cf

# [colors-dark]
# alpha=0.5
# foreground=e6e1cf
# background=0D0D0D
# regular0=0f1419 # black
# regular1=f07178 # red
# regular2=b8cc52 # green
# regular3=ffb454 # yellow
# regular4=59c2ff # blue
# regular5=d2a6ff # magenta
# regular6=95e6cb # cyan
# regular7=e6e1cf # white
# bright0=272d38 # bright black
# bright1=f07178 # bright red
# bright2=b8cc52 # bright green
# bright3=ffb454 # bright yellow
# bright4=59c2ff # bright blue
# bright5=d2a6ff # bright magenta
# bright6=95e6cb # bright cyan
# bright7=f3f4f5 # bright white
# 16=ff8f40
# 17=e6b673
# 18=131721
# 19=272d38
# 20=bfbdb6
# 21=e6e1cf
